package model;

import javax.persistence.*;


// Generated 2019-3-23 15:01:57 by Hibernate Tools 5.3.6.Final

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category")
public class Category implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
    @Column(name="id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	private String type;
	private Boolean hot;
	@ManyToOne(fetch=FetchType.EAGER)
	@JoinColumn(name="account_id")
	private Account account;

	public Category() {
	}

	public Category(String type, Boolean hot) {
		this.type = type;
		this.hot = hot;
	}
	public Category(int id,String type,Boolean hot) {
		this.id = id;
		this.type = type;
		this.hot = hot;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Boolean getHot() {
		return this.hot;
	}

	public void setHot(Boolean hot) {
		this.hot = hot;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

}
